module.exports = {
  projects: [
    '<rootDir>/apps/todomongoapp',
    '<rootDir>/apps/todomongoapi',
    '<rootDir>/libs/todomongoapi/controllers',
    '<rootDir>/libs/todomongoapi/modules',
    '<rootDir>/libs/todomongoapi/routes',
    '<rootDir>/libs/shared/data-access-models',
    '<rootDir>/libs/todomongoapi/services',
    '<rootDir>/libs/todomongoapi/schemas',
    '<rootDir>/apps/natoursapi',
    '<rootDir>/libs/natoursapi/controllers',
    '<rootDir>/libs/natoursapi/modules',
    '<rootDir>/libs/natoursapi/routes',
    '<rootDir>/libs/natoursapi/schemas',
    '<rootDir>/libs/natoursapi/services',
    '<rootDir>/libs/natoursapi/fake-data',
    '<rootDir>/libs/shared/environments',
    '<rootDir>/libs/natoursapi/models',
    '<rootDir>/libs/natoursapi/utils',
    '<rootDir>/libs/natoursapi/middleware',
    '<rootDir>/apps/postgresapi',
    '<rootDir>/libs/postgresapi/models',
  ],
};
